steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/bbc/datalab-python-container-microservice']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/datalab-service:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/$PROJECT_ID/datalab-service:$REVISION_ID"
  
